version: "3.8"
services:
  prometheus:
    privileged: true
    network_mode: "host"
    container_name: prometheus
    image: quay.io/prometheus/prometheus:v2.26.0
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090

  node-exporter:
    privileged: true
    network_mode: "host"
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"

  grafana:
    privileged: true
    network_mode: "host"
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  alertmanager:
    privileged: true
    network_mode: "host"
    container_name: alertmanager
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp_exporter
    volumes:
      - ./snmp_exporter/:/etc/snmp_exporter/
    ports:
      - 9116:9116
    volumes:
      - ./snmp-synology/snmp-synology.yml:/etc/snmp_exporter/snmp.yml
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"